import { mkdir, mkdtemp, readFile, rm, symlink, writeFile } from 'node:fs/promises';
import { watch } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, test } from 'vitest';
import { addLink, addPaper, emptyLedger, exportBibliography, generateBibtex, readProject } from '../src/index.js';

let root: string;
beforeEach(async () => { root = await mkdtemp(join(tmpdir(), 'citetrace-project-')); });
afterEach(async () => { await rm(root, { recursive: true, force: true }); });

describe('project reader and bibliography', () => {
  test('reads saved Python artifacts recursively while honoring ignores and reporting errors', async () => {
    await mkdir(join(root, 'src', 'ignored'), { recursive: true });
    await mkdir(join(root, 'node_modules'), { recursive: true });
    await writeFile(join(root, '.gitignore'), 'src/ignored/\n*.skip.py\n/root-only.py\n**/generated.py\n');
    await writeFile(join(root, 'src', '.gitignore'), 'local.py\n');
    await writeFile(join(root, 'src', 'keep.py'), 'def keep():\n    pass\n');
    await writeFile(join(root, 'src', 'root-only.py'), 'value = 1\n');
    await writeFile(join(root, 'root-only.py'), 'bad');
    await writeFile(join(root, 'generated.py'), 'bad');
    await writeFile(join(root, 'src', 'generated.py'), 'bad');
    await writeFile(join(root, 'src', 'local.py'), 'bad');
    await writeFile(join(root, 'src', 'ignored', 'no.py'), 'bad');
    await writeFile(join(root, 'bad.skip.py'), 'bad');
    await writeFile(join(root, 'node_modules', 'dep.py'), 'bad');
    const outside = await mkdtemp(join(tmpdir(), 'citetrace-outside-'));
    await writeFile(join(outside, 'secret.py'), 'secret = 1');
    await symlink(join(outside, 'secret.py'), join(root, 'outside.py'));
    try {
      const project = await readProject(root);
      expect(project.artifacts.map(item => item.artifact)).toEqual(['src/keep.py', 'src/root-only.py']);
      expect(project.artifacts[0]!.units[0]!.source).toContain('def keep');
    } finally { await rm(outside, { recursive: true, force: true }); }
  });

  test('exports deterministic escaped BibTeX for linked papers only and protects user files', async () => {
    const ledger = emptyLedger();
    const linked = addPaper(ledger, { title: 'A {Study} & More', authors: ['Ada Lovelace', 'A_B'], year: 2024, doi: '10.1000/x', metadataSource: 'manual' });
    addPaper(ledger, { title: 'Unlinked', authors: ['Nobody'], metadataSource: 'manual' });
    addLink(ledger, { paperId: linked.id, anchor: { schemaVersion: 1, artifact: 'a.py', unitKind: 'file', unitFingerprint: 'a'.repeat(64) }, relation: 'implements', actor: 'human' });
    const bib = generateBibtex(ledger);
    expect(bib).toContain('% Generated by CiteTrace.');
    expect(bib).toContain('title = {A \\{Study\\} \\& More}');
    expect(bib).not.toContain('Unlinked');

    await writeFile(join(root, 'references.bib'), 'mine');
    await expect(exportBibliography(root, ledger, { output: 'references.bib' })).rejects.toThrow(/owned|force/i);
    await exportBibliography(root, ledger, { output: 'references.bib', force: true });
    expect(await readFile(join(root, 'references.bib'), 'utf8')).toBe(bib);
    await expect(exportBibliography(root, ledger, { output: '../outside.bib' })).rejects.toThrow(/outside|path/i);
  });

  test('does not create output through a symlinked parent directory', async () => {
    const ledger = emptyLedger();
    const outside = await mkdtemp(join(tmpdir(), 'citetrace-bib-outside-'));
    await symlink(outside, join(root, 'linked'));
    try {
      await expect(exportBibliography(root, ledger, { output: 'linked/new/references.bib' })).rejects.toThrow(/symlink|outside/i);
      await expect(readFile(join(outside, 'new', 'references.bib'), 'utf8')).rejects.toMatchObject({ code: 'ENOENT' });
      await expect(readFile(join(outside, 'new'), 'utf8')).rejects.toMatchObject({ code: 'ENOENT' });
    } finally { await rm(outside, { recursive: true, force: true }); }
  });

  test('honors an existing cooperative output lock', async () => {
    const ledger = emptyLedger(); const target = join(root, 'references.bib'); const lock = `${target}.citetrace.lock`;
    await writeFile(lock, 'other exporter');
    await expect(exportBibliography(root, ledger, { output: 'references.bib', force: true })).rejects.toThrow(/locked|export/i);
    expect(await readFile(lock, 'utf8')).toBe('other exporter');
  });

  test.each([
    { initial: undefined, label: 'an initially absent target' },
    { initial: '% Generated by CiteTrace. Manual edits may be replaced.\n\n@article{old,\n  title = {Old}\n}\n', label: 'a generated target' },
  ])('does not overwrite a concurrent writer for $label', async ({ initial }) => {
    const ledger = emptyLedger();
    const paper = addPaper(ledger, { title: `Large ${'x'.repeat(8_000_000)}`, authors: [], metadataSource: 'manual' });
    addLink(ledger, { paperId: paper.id, anchor: { schemaVersion: 1, artifact: 'a.py', unitKind: 'file', unitFingerprint: 'a'.repeat(64) }, relation: 'implements', actor: 'human' });
    const target = join(root, 'references.bib');
    if (initial !== undefined) await writeFile(target, initial);
    let resolveTemporary!: () => void;
    const temporaryCreated = new Promise<void>(resolve => { resolveTemporary = resolve; });
    const observer = watch(root, (_event, filename) => {
      if (filename?.startsWith('references.bib.') && filename.endsWith('.tmp')) resolveTemporary();
    });
    try {
      const exporting = exportBibliography(root, ledger, { output: 'references.bib', force: true });
      await temporaryCreated;
      await writeFile(target, 'concurrent user content');
      await expect(exporting).rejects.toThrow(/changed|concurrent|exists/i);
      expect(await readFile(target, 'utf8')).toBe('concurrent user content');
    } finally { observer.close(); }
  }, 20_000);
});
