import { randomUUID } from 'node:crypto';
import { link, lstat, mkdir, open, readFile, realpath, rename, unlink } from 'node:fs/promises';
import { dirname, relative, resolve, sep } from 'node:path';
import type { Ledger, Paper } from './ledger.js';

export const BIBLIOGRAPHY_HEADER = '% Generated by CiteTrace. Manual edits may be replaced.\n';
export const DEFAULT_BIBLIOGRAPHY = 'references.citetrace.bib';
export interface BibliographyExportOptions { output?: string; force?: boolean }

function escapeBibtex(value: string): string {
  const replacements: Record<string, string> = { '\\': '\\textbackslash{}', '{': '\\{', '}': '\\}', '&': '\\&', '%': '\\%', '$': '\\$', '#': '\\#', '_': '\\_', '^': '\\^{}', '~': '\\~{}' };
  return value.replace(/[\\{}&%$#_^~]/g, character => replacements[character]!);
}

function entry(paper: Paper): string {
  const fields: Array<[string, string | number | undefined]> = [
    ['title', paper.title], ['author', paper.authors.join(' and ')], ['year', paper.year], ['doi', paper.doi], ['eprint', paper.arxiv],
    ['archivePrefix', paper.arxiv ? 'arXiv' : undefined], ['url', paper.url],
  ];
  const lines = fields.flatMap(([name, value]) => value === undefined || value === '' ? [] : [`  ${name} = {${escapeBibtex(String(value))}}`]);
  return `@article{${paper.citationKey},\n${lines.join(',\n')}\n}`;
}

export function generateBibtex(ledger: Ledger): string {
  const linked = new Set(ledger.links.map(link => link.paperId));
  const entries = ledger.papers.filter(paper => linked.has(paper.id)).sort((a, b) => a.citationKey.localeCompare(b.citationKey)).map(entry);
  return `${BIBLIOGRAPHY_HEADER}${entries.length ? `\n${entries.join('\n\n')}\n` : ''}`;
}

async function safeOutput(root: string, output: string): Promise<string> {
  const rootPath = await realpath(root); const target = resolve(rootPath, output); const rel = relative(rootPath, target);
  if (rel === '..' || rel.startsWith(`..${sep}`) || rel === '') throw new Error('Bibliography output path must be a file inside the project.');
  const parentPath = dirname(target); const parentRelative = relative(rootPath, parentPath); let current = rootPath;
  for (const part of parentRelative === '' ? [] : parentRelative.split(sep)) {
    current = resolve(current, part!);
    try {
      const stat = await lstat(current);
      if (stat.isSymbolicLink()) throw new Error('Bibliography output parent cannot be a symlink.');
      if (!stat.isDirectory()) throw new Error('Bibliography output parent must be a directory.');
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
      await mkdir(current);
    }
  }
  const parent = await realpath(parentPath);
  if (parent !== rootPath && !parent.startsWith(`${rootPath}${sep}`)) throw new Error('Bibliography output path resolves outside the project.');
  try { if ((await lstat(target)).isSymbolicLink()) throw new Error('Bibliography output cannot be a symlink.'); }
  catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; }
  return target;
}

export async function exportBibliography(root: string, ledger: Ledger, options: BibliographyExportOptions = {}): Promise<string> {
  const output = options.output ?? DEFAULT_BIBLIOGRAPHY; const target = await safeOutput(root, output);
  const contents = generateBibtex(ledger); const lockPath = `${target}.citetrace.lock`;
  let lock;
  try {
    lock = await open(lockPath, 'wx', 0o600);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'EEXIST') throw new Error('Bibliography export is locked by another writer; retry after it finishes.');
    throw error;
  }
  const temporary = `${target}.${process.pid}.${randomUUID()}.tmp`; let expected: string | null = null;
  try {
    await lock.writeFile(`${JSON.stringify({ pid: process.pid, createdAt: new Date().toISOString() })}\n`, 'utf8');
    try {
      expected = await readFile(target, 'utf8');
      if (!options.force && !expected.startsWith(BIBLIOGRAPHY_HEADER)) throw new Error('Refusing to overwrite a user-owned bibliography; pass --force to replace it.');
    } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; }
    const file = await open(temporary, 'wx', 0o600); try { await file.writeFile(contents, 'utf8'); await file.sync(); } finally { await file.close(); }
    if (expected === null) {
      try { await link(temporary, target); }
      catch (error) {
        if ((error as NodeJS.ErrnoException).code === 'EEXIST') throw new Error('Bibliography target was created concurrently; retry after reviewing it.');
        throw error;
      }
    } else {
      let current: string;
      try { current = await readFile(target, 'utf8'); }
      catch (error) {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') throw new Error('Bibliography target changed concurrently; retry after reviewing it.');
        throw error;
      }
      if (current !== expected) throw new Error('Bibliography target changed concurrently; retry after reviewing it.');
      await rename(temporary, target);
    }
    if (process.platform !== 'win32') { const parent = await open(dirname(target), 'r'); try { await parent.sync(); } finally { await parent.close(); } }
  } finally {
    try { await unlink(temporary).catch(error => { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; }); }
    finally {
      try { await lock.close(); }
      finally { await unlink(lockPath).catch(error => { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; }); }
    }
  }
  return output;
}
